title: Jason Odom # your name (or website title) here
logo: "/images/Portfolio Photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to My Portfolio!
  I’m a senior at California State University, Fresno, pursuing a degree in Business Administration with a concentration in Data Analytics. Here, you’ll find a collection of projects I’ve worked on that showcase my skills in data analysis, problem-solving, and leveraging technology to drive insights.
  <br><br>
  If you have any questions or would like to connect, feel free to reach out to me at jasonodom44@gmail.com. I’d love to hear from you! 
  <br><br>
  <a href="https://www.linkedin.com/in/jason-odom-21a52916a?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bd%2B0EsdRSTMmHNf6ZTdig3w%3D%3D">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-YTG3XNN7GQ # your Google Analytics tracking ID here
